version: 2

project_name: ragent

before:
  hooks:
    - go mod download

builds:
  - id: ragent
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md
      - README_ja.md

checksum:
  name_template: 'checksums_{{ .Version }}.txt'
  algorithm: sha256

changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

release:
  draft: false
  prerelease: auto
